baseURL = "http://droogmic.github.io/"
languageCode = "en-uk"
defaultContentLanguage = "en"
# publishDir = "docs"

enableRobotsTXT = true
disableKinds=["RSS"]

title = "Michael Droogleever"
theme = "droogmic-dimension"

[params]
  description = "Software engineering graduate from Cambridge University"
  logo = "fa-diamond"
  copyright = "Michael Droogleever"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/michael-droogleever"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/droogmic"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/droogmic"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.fr]
languageName = "Français"
weight = 2
title = "Michael Droogleever"
description = "Diplomé en ingénierie informatique de l'Université de Cambridge"
